-- Returns the lowest available SNUM for a student.
CREATE OR REPLACE FUNCTION LOWEST_STUDENT_NUM RETURN NUMBER 
AS
  CNUM INTEGER := 1;
  CCOUNT INTEGER := 1;
BEGIN
  WHILE TRUE
  LOOP
    SELECT COUNT(SNUM) INTO CCOUNT FROM STUDENT WHERE SNUM = CNUM;
    IF CCOUNT = 0 THEN
      RETURN CNUM;
    END IF;
    CNUM := CNUM + 1;
  END LOOP;
END LOWEST_STUDENT_NUM;